OLLAMA_HOST = "http://ollama:11434"

EMBED_MODEL = "nomic-embed-text"
CHAT_MODEL = "llama3"

CHROMA_PATH = "./data/chroma"
COLLECTION_NAME = "documents"

TOP_K = 3
MAX_CHUNK_SIZE = 1000

MIN_CHUNK_SIZE = 300

SIMILARITY_THRESHOLD = 0.88
MAX_DISTANCE = 0.85