services:
  api:
    build: .
    container_name: rag-api

    ports:
      - "8000:8000"

    volumes:
      - .:/app
      - ./data/chroma:/app/data/chroma

    depends_on:
      - ollama

    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama

    volumes:
      - ollama:/root/.ollama

    restart: unless-stopped

volumes:
  ollama: